# Generated by Django 3.2 on 2023-01-23 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='telegram_chat_id',
            field=models.CharField(max_length=100),
        ),
    ]
